---
title: "Final Exam Study Guide"
draft: false
---

Our final exam is **Monday April 27 from 9:00 AM to 12:00 PM**. You are allowed both sides of **two** 8.5" x 11" hand-written sheets of notes, prepared by you and you alone.The exam will cover the following topics:

1.  Probability spaces and rules
2.  Counting
3.  Conditional probability and independence
4.  Discrete random variables
5.  Continuous random variables
6.  The moment-generating function
7.  Transformations of random variables
8.  Joint distributions
9.  Maximum likelihood estimation
10. Bayesian inference

There will be approximately 1 problem per topic. The problems on topics 1-8 will be similar to the midterms. Since you've had more time to live with this material, I reserve the right to include problems that might stretch you a bit. For the MLE and Bayesian problems, I assure you there will be no surprises. You can expect problems that are exactly like the examples you've seen in lecture, lab, Problem Set 7, and this study guide. The distributions may be different, and the details might change, but the format and the steps are the same. If you work every practice problem from scratch on your own and then study the solutions carefully, you are ready.

::: callout-tip 
## What special distribution families should I know?
[Binomial](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/discrete-binomial.html), [geometric](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/discrete-geometric.html), [Poisson](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/discrete-poisson.html), [continuous uniform](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/continuous-uniform.html), [normal](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/continuous-normal.html), [gamma](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/continuous-gamma.html) (and its special cases like exponential),
[beta](https://anyakatsevich.github.io/sta240-s26.github.io/distributions/continuous-beta.html).

Anything else will be introduced from scratch within the exam as if you had never seen it before. 

NOTE: the distribution helpers are the authoritative resource for pdf/pmf/cdf formulas. Other Internet sources may lead you astray because some of the distribution families have alternative parameterizations, e.g. $\frac{1}{\beta}e^{-\frac{x}{\beta}}$ for Exp$(\beta)$ (which is NOT the way we define it).
:::

::: callout-note
## Reminder

If your final exam score is better than your lowest midterm score, I will replace the low midterm with the final.
:::

# 1. Probability spaces and rules

## Problem 1

{{< include bank/basic-rules/disjoint-complements.qmd >}}

## Problem 2

{{< include bank/basic-rules/bonferroni.qmd >}}

## Want more review?

- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture3.pdf) on axioms and rules;
- [Problem Set 1](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-1.html): problems 4 - 8;
- [Problem Set 2](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-2.html): problems 1 - 2;
- [Midterm 1 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-1.html#probability-spaces): problems 1 - 4;
- Midterm 1: problem 1.

# 2. Counting

## Problem 3

{{< include bank/counting/bridge.qmd >}}

## Problem 4

{{< include bank/counting/elevator.qmd >}}

## Want more review?

- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture4and5-counting.pdf)  counting theory, birthday problem, and other worked examples;
- [Lab 2](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-2.html) worked examples;
- [Problem Set 1](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-1.html): problems 9 - 10;
- [Problem Set 2](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-2.html): problems 3 - 7;
- [Problem Set 3](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-3.html): problems 1 - 2;
- [Midterm 1 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-1.html#counting): problems 5 - 7;
- Midterm 1: problems 2,5;
- Odd-numbered exercises in DeGroot & Schervish Chapters 1.6 - 1.8, 1.12.


# 3. Conditional probability and independence

## Problem 5

{{< include bank/conditional-probability/recruiter.qmd >}}

## Problem 6

{{< include bank/conditional-probability/dgs-exercise-2-3-1.qmd >}}

## Want more review?

- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture6.pdf) with worked examples;
- The lil' [app](https://anyakatsevich.github.io/sta240-s26.github.io/apps/disease-testing.html) on disease testing;
- [Problem Set 2](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-2.html): problems 8 - 9;
- [Problem Set 3](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-3.html): problems 3 - 7;
- [Problem Set 4](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-4.html): problems 1 - 2;
- [Midterm 1 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-1.html#conditional-probability): problems 8 - 10;
- Midterm 1: problem 3;
- Odd-numbered exercises in DeGroot & Schervish Chapter 2.


# 4. Discrete random variables

## Problem 7

{{< include bank/counting/streaks.qmd >}}

## Problem 8

{{< include bank/random-variables-discrete/exponential-ceiling.qmd >}}

## Want more review?

- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-notes-05-random-variables.pdf) introducing random variables;
- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture9.pdf) on special families of discrete random variables;
- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture10.pdf) on expected value;
- [Lecture notes](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-notes-08-variance.pdf) on variance;
- [Lab 5](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-5.html) exercises;
- [Problem Set 2](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-2.html): problem 6;
- [Problem Set 3](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-3.html): problems 8 - 9;
- [Problem Set 4](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-4.html): problems 3 - 9;
- [Midterm 1 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-1.html#discrete-random-variables): problems 11 - 12;
- [Midterm 2 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-2.html#discrete-random-variables): problems 1 - 2;
- Midterm 1: problems 4 and 5;
- Midterm 2: problem 2.


# 5. Continuous random variables

## Problem 9

{{< include bank/random-variables-continuous/logistic.qmd >}}

## Problem 10

{{< include bank/random-variables-continuous/weird.qmd >}}

## Want more review?


- Examples from [lecture](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture12-13.pdf);
- [Lecture 14](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture14.pdf) on normal and gamma;
- [Lab 8](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-8.html);
- [Problem Set 5](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-5.html): problems 1 - 7;
- [Problem Set 6](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-6.html): problems 1 - 2;
- [Midterm 2 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-2.html#continuous-random-variables): problems 3 - 4;
- Odd-numbered exercises in DeGroot & Schervish Chapters 3.2, 5.6, 5.7.


# 6. The moment-generating function

## Problem 11

{{< include bank/moments/direct-mgf.qmd >}}

## Problem 12

{{< include bank/moments/compound-poisson.qmd >}}

## Want more review?

- worked examples from [lecture 15](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture15.pdf) and [lecture 16](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture16.pdf);
- new theorems and examples from [lecture](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sums-and-averages.pdf) about updating MGFs under linear transformations;
- [Problem Set 5](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-5.html): problems 8 - 9;
- [Problem Set 6](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-6.html): problems 3 - 5;
- [Problem Set 7](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-7.html): problems 1 - 2;
- [Midterm 2 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-2.html#moment-generating-function): problems 11 - 12;
- Midterm 2: problem 2;
- Odd-numbered exercises in DeGroot & Schervish Chapter 4.4.


# 7. Transformations of random variables

## Problem 13 {#sec-weibull}

{{< include bank/transformations/twerkout-3.qmd >}}

## Problem 14

{{< include bank/transformations/gamma-power.qmd >}}

## Want more review?

- [Lab 7](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-7.html);
- Problem Set 6: [problem 6](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-6.html#problem-6);
- Midterm 2 Study Guide: [problem 7](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-2.html#problem-7);
- Midterm 2: problem 3;
- Read DeGroot & Schervish Chapter 3.8 and do the odd-numbered exercises.


# 8. Joint distributions

## Problem 15

{{< include bank/joint-distributions/weird-hard-thing.qmd >}}

## Problem 16

{{< include bank/joint-distributions/gamma-weibull-hierarchy.qmd >}}

## Want more review?

- jointly discrete examples from [lecture](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/lecture17.pdf);
- jointly contnuous examples from [lecture](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/joint-continuous.pdf);
- mixed Poisson-gamma example from [Lab 9](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-9.html);
- [Problem Set 6](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-6.html): problems 7 - 10;
- [Midterm 2 Study Guide](https://anyakatsevich.github.io/sta240-s26.github.io/problems/exam-midterm-2.html#joint-distributions): problems 8 - 9;
- Midterm 2: problem 4;
- Odd-numbered exercises in DeGroot & Schervish Chapters 3.4 - 3.6.


# 9. Maximum likelihood estimation

## Problem 17

{{< include bank/mle/mle-normal-mean.qmd >}}

## Problem 18

{{< include bank/mle/mle-lomax.qmd >}}

## Problem 19

{{< include bank/mle/mle-weibull.qmd >}}

## Want more review?

- Examples from [lecture 23](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-notes-mle-examples.pdf) and [lecture 24](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-mle-intro-bayes.pdf);
- [Lab 10](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-10.html);
- [Problem Set 7](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-7.html): problems 3 - 4.


# 10. Bayesian inference

## Problem 20

{{< include bank/bayes/normal-normal.qmd >}}

## Problem 21

{{< include bank/bayes/inv-gamma-normal.qmd >}}

## Problem 22

{{< include bank/bayes/gamma-lomax.qmd >}}

## Want more review?

- Examples from [lecture 24](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-mle-intro-bayes.pdf) and [lecture 25](https://anyakatsevich.github.io/sta240-s26.github.io/lecture-notes/sta240-more-bayes.pdf);
- [Lab 11](https://anyakatsevich.github.io/sta240-s26.github.io/labs/lab-11.html);
- [Problem Set 7](https://anyakatsevich.github.io/sta240-s26.github.io/problems/pset-7.html): problems 5 - 6.


